# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Replace values in .env.example
        env:
          APP_URL: ${{ vars.APP_URL }}
          VAULT_URL: ${{ vars.VAULT_URL }}
          VAULT_TOKEN: ${{ vars.VAULT_TOKEN }}
          VAULT_VERSION: ${{ vars.VAULT_VERSION }}
          VAULT_PATH: ${{ vars.VAULT_PATH }}
          DOMAIN_REGISTRY: ${{ vars.DOMAIN_REGISTRY }}
          USERNAME_REGISTRY: ${{ vars.USERNAME_REGISTRY }}
          PASSWORD_REGISTRY: ${{ vars.PASSWORD_REGISTRY }}
        run: |
          echo "APP_URL: $APP_URL"
          echo "VAULT_URL: $VAULT_URL"
          echo "VAULT_TOKEN: $VAULT_TOKEN"
          echo "VAULT_VERSION: $VAULT_VERSION"
          echo "VAULT_PATH: $VAULT_PATH"
          echo "DOMAIN_REGISTRY: $DOMAIN_REGISTRY"
          echo "USERNAME_REGISTRY: $USERNAME_REGISTRY"
          echo "PASSWORD_REGISTRY: $PASSWORD_REGISTRY"
